FROM jinaai/jina:master-py37-perf

COPY gpu_requirements.txt gpu_requirements.txt
RUN pip install -r gpu_requirements.txt

COPY . /workdir/
WORKDIR /workdir

ENTRYPOINT ["jina", "executor", "--uses", "config.yml"]
